apiVersion: io.klira.franz/v0
kind: Franz
metadata:
  name: example
runtime:
  supervisor:
    tasks:
      - worker:
          className: io.klira.franz.examples.ExampleSW
        plugins:
          - className: io.klira.franz.engine.plugins.kafka.CommitManager
          - className: io.klira.franz.engine.plugins.kafka.KafkaConsumerPlugin
            options:
              topics:
                - test
              kafkaOptions:
          - className: io.klira.franz.engine.plugins.retry.RetryManager